// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_MESSAGEPROTOCOL_PROTOCOL_H_
#define FLATBUFFERS_GENERATED_MESSAGEPROTOCOL_PROTOCOL_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 2 &&
              FLATBUFFERS_VERSION_REVISION == 10,
             "Non-compatible flatbuffers version included");

namespace protocol {

struct REQUEST_CONNECT;
struct REQUEST_CONNECTBuilder;

struct RESPONSE_CONNECT;
struct RESPONSE_CONNECTBuilder;

struct NOTICE_KICK;
struct NOTICE_KICKBuilder;

struct REQUEST_DISCONNECT;
struct REQUEST_DISCONNECTBuilder;

struct RESPONSE_DISCONNECT;
struct RESPONSE_DISCONNECTBuilder;

struct REQUEST_HEARTBEAT;
struct REQUEST_HEARTBEATBuilder;

struct RESPONSE_HEARTBEAT;
struct RESPONSE_HEARTBEATBuilder;

struct MESSAGE_PROTOCOL;
struct MESSAGE_PROTOCOLBuilder;

enum MESSAGETYPE : int32_t {
  MESSAGETYPE_BEGIN = 0,
  MESSAGETYPE_REQUEST_CONNECT = 1,
  MESSAGETYPE_RESPONSE_CONNECT = 2,
  MESSAGETYPE_REQUEST_DISCONNECT = 3,
  MESSAGETYPE_RESPONSE_DISCONNECT = 4,
  MESSAGETYPE_NOTICE_KICK = 5,
  MESSAGETYPE_REQUEST_HEARTBEAT = 6,
  MESSAGETYPE_RESPONSE_HEARTBEAT = 7,
  MESSAGETYPE_END = 8,
  MESSAGETYPE_MIN = MESSAGETYPE_BEGIN,
  MESSAGETYPE_MAX = MESSAGETYPE_END
};

inline const MESSAGETYPE (&EnumValuesMESSAGETYPE())[9] {
  static const MESSAGETYPE values[] = {
    MESSAGETYPE_BEGIN,
    MESSAGETYPE_REQUEST_CONNECT,
    MESSAGETYPE_RESPONSE_CONNECT,
    MESSAGETYPE_REQUEST_DISCONNECT,
    MESSAGETYPE_RESPONSE_DISCONNECT,
    MESSAGETYPE_NOTICE_KICK,
    MESSAGETYPE_REQUEST_HEARTBEAT,
    MESSAGETYPE_RESPONSE_HEARTBEAT,
    MESSAGETYPE_END
  };
  return values;
}

inline const char * const *EnumNamesMESSAGETYPE() {
  static const char * const names[10] = {
    "BEGIN",
    "REQUEST_CONNECT",
    "RESPONSE_CONNECT",
    "REQUEST_DISCONNECT",
    "RESPONSE_DISCONNECT",
    "NOTICE_KICK",
    "REQUEST_HEARTBEAT",
    "RESPONSE_HEARTBEAT",
    "END",
    nullptr
  };
  return names;
}

inline const char *EnumNameMESSAGETYPE(MESSAGETYPE e) {
  if (::flatbuffers::IsOutRange(e, MESSAGETYPE_BEGIN, MESSAGETYPE_END)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesMESSAGETYPE()[index];
}

enum Content : uint8_t {
  Content_NONE = 0,
  Content_REQUEST_CONNECT = 1,
  Content_RESPONSE_CONNECT = 2,
  Content_REQUEST_DISCONNECT = 3,
  Content_RESPONSE_DISCONNECT = 4,
  Content_NOTICE_KICK = 5,
  Content_REQUEST_HEARTBEAT = 6,
  Content_RESPONSE_HEARTBEAT = 7,
  Content_MIN = Content_NONE,
  Content_MAX = Content_RESPONSE_HEARTBEAT
};

inline const Content (&EnumValuesContent())[8] {
  static const Content values[] = {
    Content_NONE,
    Content_REQUEST_CONNECT,
    Content_RESPONSE_CONNECT,
    Content_REQUEST_DISCONNECT,
    Content_RESPONSE_DISCONNECT,
    Content_NOTICE_KICK,
    Content_REQUEST_HEARTBEAT,
    Content_RESPONSE_HEARTBEAT
  };
  return values;
}

inline const char * const *EnumNamesContent() {
  static const char * const names[9] = {
    "NONE",
    "REQUEST_CONNECT",
    "RESPONSE_CONNECT",
    "REQUEST_DISCONNECT",
    "RESPONSE_DISCONNECT",
    "NOTICE_KICK",
    "REQUEST_HEARTBEAT",
    "RESPONSE_HEARTBEAT",
    nullptr
  };
  return names;
}

inline const char *EnumNameContent(Content e) {
  if (::flatbuffers::IsOutRange(e, Content_NONE, Content_RESPONSE_HEARTBEAT)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesContent()[index];
}

template<typename T> struct ContentTraits {
  static const Content enum_value = Content_NONE;
};

template<> struct ContentTraits<protocol::REQUEST_CONNECT> {
  static const Content enum_value = Content_REQUEST_CONNECT;
};

template<> struct ContentTraits<protocol::RESPONSE_CONNECT> {
  static const Content enum_value = Content_RESPONSE_CONNECT;
};

template<> struct ContentTraits<protocol::REQUEST_DISCONNECT> {
  static const Content enum_value = Content_REQUEST_DISCONNECT;
};

template<> struct ContentTraits<protocol::RESPONSE_DISCONNECT> {
  static const Content enum_value = Content_RESPONSE_DISCONNECT;
};

template<> struct ContentTraits<protocol::NOTICE_KICK> {
  static const Content enum_value = Content_NOTICE_KICK;
};

template<> struct ContentTraits<protocol::REQUEST_HEARTBEAT> {
  static const Content enum_value = Content_REQUEST_HEARTBEAT;
};

template<> struct ContentTraits<protocol::RESPONSE_HEARTBEAT> {
  static const Content enum_value = Content_RESPONSE_HEARTBEAT;
};

bool VerifyContent(::flatbuffers::Verifier &verifier, const void *obj, Content type);
bool VerifyContentVector(::flatbuffers::Verifier &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types);

struct REQUEST_CONNECT FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef REQUEST_CONNECTBuilder Builder;
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           verifier.EndTable();
  }
};

struct REQUEST_CONNECTBuilder {
  typedef REQUEST_CONNECT Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  explicit REQUEST_CONNECTBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<REQUEST_CONNECT> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<REQUEST_CONNECT>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<REQUEST_CONNECT> CreateREQUEST_CONNECT(
    ::flatbuffers::FlatBufferBuilder &_fbb) {
  REQUEST_CONNECTBuilder builder_(_fbb);
  return builder_.Finish();
}

struct RESPONSE_CONNECT FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef RESPONSE_CONNECTBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_FEEDBACK = 4
  };
  bool feedback() const {
    return GetField<uint8_t>(VT_FEEDBACK, 0) != 0;
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_FEEDBACK, 1) &&
           verifier.EndTable();
  }
};

struct RESPONSE_CONNECTBuilder {
  typedef RESPONSE_CONNECT Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_feedback(bool feedback) {
    fbb_.AddElement<uint8_t>(RESPONSE_CONNECT::VT_FEEDBACK, static_cast<uint8_t>(feedback), 0);
  }
  explicit RESPONSE_CONNECTBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<RESPONSE_CONNECT> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<RESPONSE_CONNECT>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<RESPONSE_CONNECT> CreateRESPONSE_CONNECT(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    bool feedback = false) {
  RESPONSE_CONNECTBuilder builder_(_fbb);
  builder_.add_feedback(feedback);
  return builder_.Finish();
}

struct NOTICE_KICK FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef NOTICE_KICKBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_COMPLETIONKEY = 4
  };
  uint32_t completionkey() const {
    return GetField<uint32_t>(VT_COMPLETIONKEY, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_COMPLETIONKEY, 4) &&
           verifier.EndTable();
  }
};

struct NOTICE_KICKBuilder {
  typedef NOTICE_KICK Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_completionkey(uint32_t completionkey) {
    fbb_.AddElement<uint32_t>(NOTICE_KICK::VT_COMPLETIONKEY, completionkey, 0);
  }
  explicit NOTICE_KICKBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<NOTICE_KICK> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<NOTICE_KICK>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<NOTICE_KICK> CreateNOTICE_KICK(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t completionkey = 0) {
  NOTICE_KICKBuilder builder_(_fbb);
  builder_.add_completionkey(completionkey);
  return builder_.Finish();
}

struct REQUEST_DISCONNECT FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef REQUEST_DISCONNECTBuilder Builder;
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           verifier.EndTable();
  }
};

struct REQUEST_DISCONNECTBuilder {
  typedef REQUEST_DISCONNECT Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  explicit REQUEST_DISCONNECTBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<REQUEST_DISCONNECT> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<REQUEST_DISCONNECT>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<REQUEST_DISCONNECT> CreateREQUEST_DISCONNECT(
    ::flatbuffers::FlatBufferBuilder &_fbb) {
  REQUEST_DISCONNECTBuilder builder_(_fbb);
  return builder_.Finish();
}

struct RESPONSE_DISCONNECT FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef RESPONSE_DISCONNECTBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_FEEDBACK = 4
  };
  bool feedback() const {
    return GetField<uint8_t>(VT_FEEDBACK, 0) != 0;
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_FEEDBACK, 1) &&
           verifier.EndTable();
  }
};

struct RESPONSE_DISCONNECTBuilder {
  typedef RESPONSE_DISCONNECT Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_feedback(bool feedback) {
    fbb_.AddElement<uint8_t>(RESPONSE_DISCONNECT::VT_FEEDBACK, static_cast<uint8_t>(feedback), 0);
  }
  explicit RESPONSE_DISCONNECTBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<RESPONSE_DISCONNECT> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<RESPONSE_DISCONNECT>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<RESPONSE_DISCONNECT> CreateRESPONSE_DISCONNECT(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    bool feedback = false) {
  RESPONSE_DISCONNECTBuilder builder_(_fbb);
  builder_.add_feedback(feedback);
  return builder_.Finish();
}

struct REQUEST_HEARTBEAT FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef REQUEST_HEARTBEATBuilder Builder;
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           verifier.EndTable();
  }
};

struct REQUEST_HEARTBEATBuilder {
  typedef REQUEST_HEARTBEAT Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  explicit REQUEST_HEARTBEATBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<REQUEST_HEARTBEAT> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<REQUEST_HEARTBEAT>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<REQUEST_HEARTBEAT> CreateREQUEST_HEARTBEAT(
    ::flatbuffers::FlatBufferBuilder &_fbb) {
  REQUEST_HEARTBEATBuilder builder_(_fbb);
  return builder_.Finish();
}

struct RESPONSE_HEARTBEAT FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef RESPONSE_HEARTBEATBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_FEEDBACK = 4
  };
  bool feedback() const {
    return GetField<uint8_t>(VT_FEEDBACK, 0) != 0;
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_FEEDBACK, 1) &&
           verifier.EndTable();
  }
};

struct RESPONSE_HEARTBEATBuilder {
  typedef RESPONSE_HEARTBEAT Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_feedback(bool feedback) {
    fbb_.AddElement<uint8_t>(RESPONSE_HEARTBEAT::VT_FEEDBACK, static_cast<uint8_t>(feedback), 0);
  }
  explicit RESPONSE_HEARTBEATBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<RESPONSE_HEARTBEAT> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<RESPONSE_HEARTBEAT>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<RESPONSE_HEARTBEAT> CreateRESPONSE_HEARTBEAT(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    bool feedback = false) {
  RESPONSE_HEARTBEATBuilder builder_(_fbb);
  builder_.add_feedback(feedback);
  return builder_.Finish();
}

struct MESSAGE_PROTOCOL FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef MESSAGE_PROTOCOLBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_MESSAGE_TYPE = 4,
    VT_CONTENT_TYPE = 6,
    VT_CONTENT = 8
  };
  protocol::MESSAGETYPE message_type() const {
    return static_cast<protocol::MESSAGETYPE>(GetField<int32_t>(VT_MESSAGE_TYPE, 0));
  }
  protocol::Content content_type() const {
    return static_cast<protocol::Content>(GetField<uint8_t>(VT_CONTENT_TYPE, 0));
  }
  const void *content() const {
    return GetPointer<const void *>(VT_CONTENT);
  }
  template<typename T> const T *content_as() const;
  const protocol::REQUEST_CONNECT *content_as_REQUEST_CONNECT() const {
    return content_type() == protocol::Content_REQUEST_CONNECT ? static_cast<const protocol::REQUEST_CONNECT *>(content()) : nullptr;
  }
  const protocol::RESPONSE_CONNECT *content_as_RESPONSE_CONNECT() const {
    return content_type() == protocol::Content_RESPONSE_CONNECT ? static_cast<const protocol::RESPONSE_CONNECT *>(content()) : nullptr;
  }
  const protocol::REQUEST_DISCONNECT *content_as_REQUEST_DISCONNECT() const {
    return content_type() == protocol::Content_REQUEST_DISCONNECT ? static_cast<const protocol::REQUEST_DISCONNECT *>(content()) : nullptr;
  }
  const protocol::RESPONSE_DISCONNECT *content_as_RESPONSE_DISCONNECT() const {
    return content_type() == protocol::Content_RESPONSE_DISCONNECT ? static_cast<const protocol::RESPONSE_DISCONNECT *>(content()) : nullptr;
  }
  const protocol::NOTICE_KICK *content_as_NOTICE_KICK() const {
    return content_type() == protocol::Content_NOTICE_KICK ? static_cast<const protocol::NOTICE_KICK *>(content()) : nullptr;
  }
  const protocol::REQUEST_HEARTBEAT *content_as_REQUEST_HEARTBEAT() const {
    return content_type() == protocol::Content_REQUEST_HEARTBEAT ? static_cast<const protocol::REQUEST_HEARTBEAT *>(content()) : nullptr;
  }
  const protocol::RESPONSE_HEARTBEAT *content_as_RESPONSE_HEARTBEAT() const {
    return content_type() == protocol::Content_RESPONSE_HEARTBEAT ? static_cast<const protocol::RESPONSE_HEARTBEAT *>(content()) : nullptr;
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_MESSAGE_TYPE, 4) &&
           VerifyField<uint8_t>(verifier, VT_CONTENT_TYPE, 1) &&
           VerifyOffset(verifier, VT_CONTENT) &&
           VerifyContent(verifier, content(), content_type()) &&
           verifier.EndTable();
  }
};

template<> inline const protocol::REQUEST_CONNECT *MESSAGE_PROTOCOL::content_as<protocol::REQUEST_CONNECT>() const {
  return content_as_REQUEST_CONNECT();
}

template<> inline const protocol::RESPONSE_CONNECT *MESSAGE_PROTOCOL::content_as<protocol::RESPONSE_CONNECT>() const {
  return content_as_RESPONSE_CONNECT();
}

template<> inline const protocol::REQUEST_DISCONNECT *MESSAGE_PROTOCOL::content_as<protocol::REQUEST_DISCONNECT>() const {
  return content_as_REQUEST_DISCONNECT();
}

template<> inline const protocol::RESPONSE_DISCONNECT *MESSAGE_PROTOCOL::content_as<protocol::RESPONSE_DISCONNECT>() const {
  return content_as_RESPONSE_DISCONNECT();
}

template<> inline const protocol::NOTICE_KICK *MESSAGE_PROTOCOL::content_as<protocol::NOTICE_KICK>() const {
  return content_as_NOTICE_KICK();
}

template<> inline const protocol::REQUEST_HEARTBEAT *MESSAGE_PROTOCOL::content_as<protocol::REQUEST_HEARTBEAT>() const {
  return content_as_REQUEST_HEARTBEAT();
}

template<> inline const protocol::RESPONSE_HEARTBEAT *MESSAGE_PROTOCOL::content_as<protocol::RESPONSE_HEARTBEAT>() const {
  return content_as_RESPONSE_HEARTBEAT();
}

struct MESSAGE_PROTOCOLBuilder {
  typedef MESSAGE_PROTOCOL Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_message_type(protocol::MESSAGETYPE message_type) {
    fbb_.AddElement<int32_t>(MESSAGE_PROTOCOL::VT_MESSAGE_TYPE, static_cast<int32_t>(message_type), 0);
  }
  void add_content_type(protocol::Content content_type) {
    fbb_.AddElement<uint8_t>(MESSAGE_PROTOCOL::VT_CONTENT_TYPE, static_cast<uint8_t>(content_type), 0);
  }
  void add_content(::flatbuffers::Offset<void> content) {
    fbb_.AddOffset(MESSAGE_PROTOCOL::VT_CONTENT, content);
  }
  explicit MESSAGE_PROTOCOLBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<MESSAGE_PROTOCOL> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<MESSAGE_PROTOCOL>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<MESSAGE_PROTOCOL> CreateMESSAGE_PROTOCOL(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    protocol::MESSAGETYPE message_type = protocol::MESSAGETYPE_BEGIN,
    protocol::Content content_type = protocol::Content_NONE,
    ::flatbuffers::Offset<void> content = 0) {
  MESSAGE_PROTOCOLBuilder builder_(_fbb);
  builder_.add_content(content);
  builder_.add_message_type(message_type);
  builder_.add_content_type(content_type);
  return builder_.Finish();
}

inline bool VerifyContent(::flatbuffers::Verifier &verifier, const void *obj, Content type) {
  switch (type) {
    case Content_NONE: {
      return true;
    }
    case Content_REQUEST_CONNECT: {
      auto ptr = reinterpret_cast<const protocol::REQUEST_CONNECT *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Content_RESPONSE_CONNECT: {
      auto ptr = reinterpret_cast<const protocol::RESPONSE_CONNECT *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Content_REQUEST_DISCONNECT: {
      auto ptr = reinterpret_cast<const protocol::REQUEST_DISCONNECT *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Content_RESPONSE_DISCONNECT: {
      auto ptr = reinterpret_cast<const protocol::RESPONSE_DISCONNECT *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Content_NOTICE_KICK: {
      auto ptr = reinterpret_cast<const protocol::NOTICE_KICK *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Content_REQUEST_HEARTBEAT: {
      auto ptr = reinterpret_cast<const protocol::REQUEST_HEARTBEAT *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Content_RESPONSE_HEARTBEAT: {
      auto ptr = reinterpret_cast<const protocol::RESPONSE_HEARTBEAT *>(obj);
      return verifier.VerifyTable(ptr);
    }
    default: return true;
  }
}

inline bool VerifyContentVector(::flatbuffers::Verifier &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types) {
  if (!values || !types) return !values && !types;
  if (values->size() != types->size()) return false;
  for (::flatbuffers::uoffset_t i = 0; i < values->size(); ++i) {
    if (!VerifyContent(
        verifier,  values->Get(i), types->GetEnum<Content>(i))) {
      return false;
    }
  }
  return true;
}

inline const protocol::MESSAGE_PROTOCOL *GetMESSAGE_PROTOCOL(const void *buf) {
  return ::flatbuffers::GetRoot<protocol::MESSAGE_PROTOCOL>(buf);
}

inline const protocol::MESSAGE_PROTOCOL *GetSizePrefixedMESSAGE_PROTOCOL(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<protocol::MESSAGE_PROTOCOL>(buf);
}

inline bool VerifyMESSAGE_PROTOCOLBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<protocol::MESSAGE_PROTOCOL>(nullptr);
}

inline bool VerifySizePrefixedMESSAGE_PROTOCOLBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<protocol::MESSAGE_PROTOCOL>(nullptr);
}

inline void FinishMESSAGE_PROTOCOLBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<protocol::MESSAGE_PROTOCOL> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedMESSAGE_PROTOCOLBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<protocol::MESSAGE_PROTOCOL> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace protocol

#endif  // FLATBUFFERS_GENERATED_MESSAGEPROTOCOL_PROTOCOL_H_
