// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_NETWORKPROTOCOL_PROTOCOL_H_
#define FLATBUFFERS_GENERATED_NETWORKPROTOCOL_PROTOCOL_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 2 &&
              FLATBUFFERS_VERSION_REVISION == 10,
             "Non-compatible flatbuffers version included");

namespace protocol {

struct INNER_CLOSE_CLIENT;
struct INNER_CLOSE_CLIENTBuilder;

struct REQUEST_REGISTER;
struct REQUEST_REGISTERBuilder;

struct RESPONSE_REGISTER;
struct RESPONSE_REGISTERBuilder;

struct REQUEST_HEARTBEAT;
struct REQUEST_HEARTBEATBuilder;

struct RESPONSE_HEARTBEAT;
struct RESPONSE_HEARTBEATBuilder;

struct NETWORK_PROTOCOL;
struct NETWORK_PROTOCOLBuilder;

enum MESSAGETYPE : int32_t {
  MESSAGETYPE_BEGIN = 0,
  MESSAGETYPE_INNER_CLOSE_CLIENT = 1,
  MESSAGETYPE_REQUEST_REGISTER = 2,
  MESSAGETYPE_RESPONSE_REGISTER = 3,
  MESSAGETYPE_REQUEST_HEARTBEAT = 4,
  MESSAGETYPE_RESPONSE_HEARTBEAT = 5,
  MESSAGETYPE_END = 6,
  MESSAGETYPE_MIN = MESSAGETYPE_BEGIN,
  MESSAGETYPE_MAX = MESSAGETYPE_END
};

inline const MESSAGETYPE (&EnumValuesMESSAGETYPE())[7] {
  static const MESSAGETYPE values[] = {
    MESSAGETYPE_BEGIN,
    MESSAGETYPE_INNER_CLOSE_CLIENT,
    MESSAGETYPE_REQUEST_REGISTER,
    MESSAGETYPE_RESPONSE_REGISTER,
    MESSAGETYPE_REQUEST_HEARTBEAT,
    MESSAGETYPE_RESPONSE_HEARTBEAT,
    MESSAGETYPE_END
  };
  return values;
}

inline const char * const *EnumNamesMESSAGETYPE() {
  static const char * const names[8] = {
    "BEGIN",
    "INNER_CLOSE_CLIENT",
    "REQUEST_REGISTER",
    "RESPONSE_REGISTER",
    "REQUEST_HEARTBEAT",
    "RESPONSE_HEARTBEAT",
    "END",
    nullptr
  };
  return names;
}

inline const char *EnumNameMESSAGETYPE(MESSAGETYPE e) {
  if (::flatbuffers::IsOutRange(e, MESSAGETYPE_BEGIN, MESSAGETYPE_END)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesMESSAGETYPE()[index];
}

enum Content : uint8_t {
  Content_NONE = 0,
  Content_INNER_CLOSE_CLIENT = 1,
  Content_REQUEST_REGISTER = 2,
  Content_RESPONSE_REGISTER = 3,
  Content_REQUEST_HEARTBEAT = 4,
  Content_RESPONSE_HEARTBEAT = 5,
  Content_MIN = Content_NONE,
  Content_MAX = Content_RESPONSE_HEARTBEAT
};

inline const Content (&EnumValuesContent())[6] {
  static const Content values[] = {
    Content_NONE,
    Content_INNER_CLOSE_CLIENT,
    Content_REQUEST_REGISTER,
    Content_RESPONSE_REGISTER,
    Content_REQUEST_HEARTBEAT,
    Content_RESPONSE_HEARTBEAT
  };
  return values;
}

inline const char * const *EnumNamesContent() {
  static const char * const names[7] = {
    "NONE",
    "INNER_CLOSE_CLIENT",
    "REQUEST_REGISTER",
    "RESPONSE_REGISTER",
    "REQUEST_HEARTBEAT",
    "RESPONSE_HEARTBEAT",
    nullptr
  };
  return names;
}

inline const char *EnumNameContent(Content e) {
  if (::flatbuffers::IsOutRange(e, Content_NONE, Content_RESPONSE_HEARTBEAT)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesContent()[index];
}

template<typename T> struct ContentTraits {
  static const Content enum_value = Content_NONE;
};

template<> struct ContentTraits<protocol::INNER_CLOSE_CLIENT> {
  static const Content enum_value = Content_INNER_CLOSE_CLIENT;
};

template<> struct ContentTraits<protocol::REQUEST_REGISTER> {
  static const Content enum_value = Content_REQUEST_REGISTER;
};

template<> struct ContentTraits<protocol::RESPONSE_REGISTER> {
  static const Content enum_value = Content_RESPONSE_REGISTER;
};

template<> struct ContentTraits<protocol::REQUEST_HEARTBEAT> {
  static const Content enum_value = Content_REQUEST_HEARTBEAT;
};

template<> struct ContentTraits<protocol::RESPONSE_HEARTBEAT> {
  static const Content enum_value = Content_RESPONSE_HEARTBEAT;
};

bool VerifyContent(::flatbuffers::Verifier &verifier, const void *obj, Content type);
bool VerifyContentVector(::flatbuffers::Verifier &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types);

struct INNER_CLOSE_CLIENT FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef INNER_CLOSE_CLIENTBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_COMPLETIONKEY = 4
  };
  uint32_t completionkey() const {
    return GetField<uint32_t>(VT_COMPLETIONKEY, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_COMPLETIONKEY, 4) &&
           verifier.EndTable();
  }
};

struct INNER_CLOSE_CLIENTBuilder {
  typedef INNER_CLOSE_CLIENT Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_completionkey(uint32_t completionkey) {
    fbb_.AddElement<uint32_t>(INNER_CLOSE_CLIENT::VT_COMPLETIONKEY, completionkey, 0);
  }
  explicit INNER_CLOSE_CLIENTBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<INNER_CLOSE_CLIENT> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<INNER_CLOSE_CLIENT>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<INNER_CLOSE_CLIENT> CreateINNER_CLOSE_CLIENT(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t completionkey = 0) {
  INNER_CLOSE_CLIENTBuilder builder_(_fbb);
  builder_.add_completionkey(completionkey);
  return builder_.Finish();
}

struct REQUEST_REGISTER FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef REQUEST_REGISTERBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SERVER_NAME = 4,
    VT_SECRET_KEY = 6
  };
  const ::flatbuffers::String *server_name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_SERVER_NAME);
  }
  const ::flatbuffers::String *secret_key() const {
    return GetPointer<const ::flatbuffers::String *>(VT_SECRET_KEY);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_SERVER_NAME) &&
           verifier.VerifyString(server_name()) &&
           VerifyOffset(verifier, VT_SECRET_KEY) &&
           verifier.VerifyString(secret_key()) &&
           verifier.EndTable();
  }
};

struct REQUEST_REGISTERBuilder {
  typedef REQUEST_REGISTER Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_server_name(::flatbuffers::Offset<::flatbuffers::String> server_name) {
    fbb_.AddOffset(REQUEST_REGISTER::VT_SERVER_NAME, server_name);
  }
  void add_secret_key(::flatbuffers::Offset<::flatbuffers::String> secret_key) {
    fbb_.AddOffset(REQUEST_REGISTER::VT_SECRET_KEY, secret_key);
  }
  explicit REQUEST_REGISTERBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<REQUEST_REGISTER> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<REQUEST_REGISTER>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<REQUEST_REGISTER> CreateREQUEST_REGISTER(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> server_name = 0,
    ::flatbuffers::Offset<::flatbuffers::String> secret_key = 0) {
  REQUEST_REGISTERBuilder builder_(_fbb);
  builder_.add_secret_key(secret_key);
  builder_.add_server_name(server_name);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<REQUEST_REGISTER> CreateREQUEST_REGISTERDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *server_name = nullptr,
    const char *secret_key = nullptr) {
  auto server_name__ = server_name ? _fbb.CreateString(server_name) : 0;
  auto secret_key__ = secret_key ? _fbb.CreateString(secret_key) : 0;
  return protocol::CreateREQUEST_REGISTER(
      _fbb,
      server_name__,
      secret_key__);
}

struct RESPONSE_REGISTER FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef RESPONSE_REGISTERBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_FEEDBACK = 4
  };
  bool feedback() const {
    return GetField<uint8_t>(VT_FEEDBACK, 0) != 0;
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_FEEDBACK, 1) &&
           verifier.EndTable();
  }
};

struct RESPONSE_REGISTERBuilder {
  typedef RESPONSE_REGISTER Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_feedback(bool feedback) {
    fbb_.AddElement<uint8_t>(RESPONSE_REGISTER::VT_FEEDBACK, static_cast<uint8_t>(feedback), 0);
  }
  explicit RESPONSE_REGISTERBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<RESPONSE_REGISTER> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<RESPONSE_REGISTER>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<RESPONSE_REGISTER> CreateRESPONSE_REGISTER(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    bool feedback = false) {
  RESPONSE_REGISTERBuilder builder_(_fbb);
  builder_.add_feedback(feedback);
  return builder_.Finish();
}

struct REQUEST_HEARTBEAT FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef REQUEST_HEARTBEATBuilder Builder;
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           verifier.EndTable();
  }
};

struct REQUEST_HEARTBEATBuilder {
  typedef REQUEST_HEARTBEAT Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  explicit REQUEST_HEARTBEATBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<REQUEST_HEARTBEAT> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<REQUEST_HEARTBEAT>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<REQUEST_HEARTBEAT> CreateREQUEST_HEARTBEAT(
    ::flatbuffers::FlatBufferBuilder &_fbb) {
  REQUEST_HEARTBEATBuilder builder_(_fbb);
  return builder_.Finish();
}

struct RESPONSE_HEARTBEAT FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef RESPONSE_HEARTBEATBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_FEEDBACK = 4
  };
  bool feedback() const {
    return GetField<uint8_t>(VT_FEEDBACK, 0) != 0;
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_FEEDBACK, 1) &&
           verifier.EndTable();
  }
};

struct RESPONSE_HEARTBEATBuilder {
  typedef RESPONSE_HEARTBEAT Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_feedback(bool feedback) {
    fbb_.AddElement<uint8_t>(RESPONSE_HEARTBEAT::VT_FEEDBACK, static_cast<uint8_t>(feedback), 0);
  }
  explicit RESPONSE_HEARTBEATBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<RESPONSE_HEARTBEAT> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<RESPONSE_HEARTBEAT>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<RESPONSE_HEARTBEAT> CreateRESPONSE_HEARTBEAT(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    bool feedback = false) {
  RESPONSE_HEARTBEATBuilder builder_(_fbb);
  builder_.add_feedback(feedback);
  return builder_.Finish();
}

struct NETWORK_PROTOCOL FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef NETWORK_PROTOCOLBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_MESSAGE_TYPE = 4,
    VT_CONTENT_TYPE = 6,
    VT_CONTENT = 8
  };
  protocol::MESSAGETYPE message_type() const {
    return static_cast<protocol::MESSAGETYPE>(GetField<int32_t>(VT_MESSAGE_TYPE, 0));
  }
  protocol::Content content_type() const {
    return static_cast<protocol::Content>(GetField<uint8_t>(VT_CONTENT_TYPE, 0));
  }
  const void *content() const {
    return GetPointer<const void *>(VT_CONTENT);
  }
  template<typename T> const T *content_as() const;
  const protocol::INNER_CLOSE_CLIENT *content_as_INNER_CLOSE_CLIENT() const {
    return content_type() == protocol::Content_INNER_CLOSE_CLIENT ? static_cast<const protocol::INNER_CLOSE_CLIENT *>(content()) : nullptr;
  }
  const protocol::REQUEST_REGISTER *content_as_REQUEST_REGISTER() const {
    return content_type() == protocol::Content_REQUEST_REGISTER ? static_cast<const protocol::REQUEST_REGISTER *>(content()) : nullptr;
  }
  const protocol::RESPONSE_REGISTER *content_as_RESPONSE_REGISTER() const {
    return content_type() == protocol::Content_RESPONSE_REGISTER ? static_cast<const protocol::RESPONSE_REGISTER *>(content()) : nullptr;
  }
  const protocol::REQUEST_HEARTBEAT *content_as_REQUEST_HEARTBEAT() const {
    return content_type() == protocol::Content_REQUEST_HEARTBEAT ? static_cast<const protocol::REQUEST_HEARTBEAT *>(content()) : nullptr;
  }
  const protocol::RESPONSE_HEARTBEAT *content_as_RESPONSE_HEARTBEAT() const {
    return content_type() == protocol::Content_RESPONSE_HEARTBEAT ? static_cast<const protocol::RESPONSE_HEARTBEAT *>(content()) : nullptr;
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_MESSAGE_TYPE, 4) &&
           VerifyField<uint8_t>(verifier, VT_CONTENT_TYPE, 1) &&
           VerifyOffset(verifier, VT_CONTENT) &&
           VerifyContent(verifier, content(), content_type()) &&
           verifier.EndTable();
  }
};

template<> inline const protocol::INNER_CLOSE_CLIENT *NETWORK_PROTOCOL::content_as<protocol::INNER_CLOSE_CLIENT>() const {
  return content_as_INNER_CLOSE_CLIENT();
}

template<> inline const protocol::REQUEST_REGISTER *NETWORK_PROTOCOL::content_as<protocol::REQUEST_REGISTER>() const {
  return content_as_REQUEST_REGISTER();
}

template<> inline const protocol::RESPONSE_REGISTER *NETWORK_PROTOCOL::content_as<protocol::RESPONSE_REGISTER>() const {
  return content_as_RESPONSE_REGISTER();
}

template<> inline const protocol::REQUEST_HEARTBEAT *NETWORK_PROTOCOL::content_as<protocol::REQUEST_HEARTBEAT>() const {
  return content_as_REQUEST_HEARTBEAT();
}

template<> inline const protocol::RESPONSE_HEARTBEAT *NETWORK_PROTOCOL::content_as<protocol::RESPONSE_HEARTBEAT>() const {
  return content_as_RESPONSE_HEARTBEAT();
}

struct NETWORK_PROTOCOLBuilder {
  typedef NETWORK_PROTOCOL Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_message_type(protocol::MESSAGETYPE message_type) {
    fbb_.AddElement<int32_t>(NETWORK_PROTOCOL::VT_MESSAGE_TYPE, static_cast<int32_t>(message_type), 0);
  }
  void add_content_type(protocol::Content content_type) {
    fbb_.AddElement<uint8_t>(NETWORK_PROTOCOL::VT_CONTENT_TYPE, static_cast<uint8_t>(content_type), 0);
  }
  void add_content(::flatbuffers::Offset<void> content) {
    fbb_.AddOffset(NETWORK_PROTOCOL::VT_CONTENT, content);
  }
  explicit NETWORK_PROTOCOLBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<NETWORK_PROTOCOL> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<NETWORK_PROTOCOL>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<NETWORK_PROTOCOL> CreateNETWORK_PROTOCOL(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    protocol::MESSAGETYPE message_type = protocol::MESSAGETYPE_BEGIN,
    protocol::Content content_type = protocol::Content_NONE,
    ::flatbuffers::Offset<void> content = 0) {
  NETWORK_PROTOCOLBuilder builder_(_fbb);
  builder_.add_content(content);
  builder_.add_message_type(message_type);
  builder_.add_content_type(content_type);
  return builder_.Finish();
}

inline bool VerifyContent(::flatbuffers::Verifier &verifier, const void *obj, Content type) {
  switch (type) {
    case Content_NONE: {
      return true;
    }
    case Content_INNER_CLOSE_CLIENT: {
      auto ptr = reinterpret_cast<const protocol::INNER_CLOSE_CLIENT *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Content_REQUEST_REGISTER: {
      auto ptr = reinterpret_cast<const protocol::REQUEST_REGISTER *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Content_RESPONSE_REGISTER: {
      auto ptr = reinterpret_cast<const protocol::RESPONSE_REGISTER *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Content_REQUEST_HEARTBEAT: {
      auto ptr = reinterpret_cast<const protocol::REQUEST_HEARTBEAT *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Content_RESPONSE_HEARTBEAT: {
      auto ptr = reinterpret_cast<const protocol::RESPONSE_HEARTBEAT *>(obj);
      return verifier.VerifyTable(ptr);
    }
    default: return true;
  }
}

inline bool VerifyContentVector(::flatbuffers::Verifier &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types) {
  if (!values || !types) return !values && !types;
  if (values->size() != types->size()) return false;
  for (::flatbuffers::uoffset_t i = 0; i < values->size(); ++i) {
    if (!VerifyContent(
        verifier,  values->Get(i), types->GetEnum<Content>(i))) {
      return false;
    }
  }
  return true;
}

inline const protocol::NETWORK_PROTOCOL *GetNETWORK_PROTOCOL(const void *buf) {
  return ::flatbuffers::GetRoot<protocol::NETWORK_PROTOCOL>(buf);
}

inline const protocol::NETWORK_PROTOCOL *GetSizePrefixedNETWORK_PROTOCOL(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<protocol::NETWORK_PROTOCOL>(buf);
}

inline bool VerifyNETWORK_PROTOCOLBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<protocol::NETWORK_PROTOCOL>(nullptr);
}

inline bool VerifySizePrefixedNETWORK_PROTOCOLBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<protocol::NETWORK_PROTOCOL>(nullptr);
}

inline void FinishNETWORK_PROTOCOLBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<protocol::NETWORK_PROTOCOL> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedNETWORK_PROTOCOLBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<protocol::NETWORK_PROTOCOL> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace protocol

#endif  // FLATBUFFERS_GENERATED_NETWORKPROTOCOL_PROTOCOL_H_
